# Generated by Django 3.2.11 on 2022-03-05 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('file_id', models.IntegerField(unique=True, verbose_name='文件编号')),
            ],
            options={
                'verbose_name': '通知文件表',
            },
        ),
    ]
