# Generated by Django 3.2.11 on 2022-03-19 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QAS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='label',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
