# Generated by Django 3.2.12 on 2022-04-02 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QAS', '0002_notice_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='desc',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='region',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
