# Generated by Django 3.2.12 on 2022-05-07 22:54

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QAS', '0004_alter_notice_file_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('upload_time', models.DateTimeField(auto_now=True, null=True, verbose_name='上传时间')),
                ('username', models.CharField(max_length=64, null=True)),
                ('file_name', models.CharField(max_length=64, null=True)),
            ],
            options={
                'verbose_name': '上传文件表',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='用户ID')),
                ('name', models.CharField(default='', max_length=30, verbose_name='姓名')),
                ('username', models.CharField(max_length=10, unique=True, verbose_name='用户名')),
                ('role', models.CharField(choices=[('0', 'Administrator'), ('1', 'Student'), ('2', 'Teacher')], default=0, max_length=30)),
                ('password', models.CharField(max_length=256, verbose_name='密码')),
                ('last_login', models.DateTimeField(auto_now=True, null=True, verbose_name='最后登录时间')),
            ],
            options={
                'verbose_name': '用户',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
